### ISSUE TITLE
multiple  `QSFP-DD` mode of operation

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/freeRtr#14]
INTEL-TOFINO2 ASIC based switch have multiple mode of operation for `QSFP-DD`:

In freeRtr `server p4lang p4` has only for example for `100GE` -> `100`

Hence `default 100GE` flavor is configured at `bf_switchd` level.

```
server p4lang p4
 export-vrf CORE
 export-port sdn1 136 400 3 0 0
 export-port sdn17001 400 100 3 2 0
 export-port sdn17002 402 100 3 2 0
 export-port sdn17003 404 100 3 2 0
 export-port sdn17004 406 100 3 2 0
 interconnect ethernet0
 vrf p4
 exit
```
In this case we should have: `100G-R2` (2 lanes) while we ended with `100G-R4` (4 lanes)

Possible values ares;
```
port-add        <port_str> <speed (1G, 10G, 25G, 40G, 40G_NB, 50G(50G/50G-R2, 50G-R2-C, 50G-R1), 100G(100G/100G-R4, 100G-R2),200G(200G/200G-R4, 200G-R8), 400G 40G_NON_BREAKABLE), 40G-R2> <fec (NONE, FC, RS)>
```

Question is how to reflect proper configuration at freeRtr level in order to cope with this new `TOFINO2` behaviour ?

**Comment by mc36** [comment]
https://github.com/rare-freertr/freeRtr/commit/2120e7d8ba8825e5ae87046f0926db527f604921 should address this at freertr level: from now on, bffwd can get "asdf" as speed so it can do whatever it wants with it....
