### ISSUE TITLE
Bump SDE version from 9.7 to 9.11.2 for RARE/freeRtr ONIE release

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/freeRtr#16]
Second RARE/freeRTr ONIE release, major change:

* Bump SDE version to 9.11.2 (plus minor patches backported to 9.12)
* Bump Linux kernel version to latest Debian stable
* Bump JRE version to latest version supported by Nix

**Comment by mc36** [comment]
this should be assigned under https://github.com/alexandergall/onie-debian-nix-installer as far as i know...
@alexandergall ?

**Comment by frederic-loui** [comment]
Hi,

The repository you mentioned in @alex repository is about creating a ONIE
installer for SDE.

Alexander might use this code. As he is crafting right now RARE/freeRtr
release 2.0,  i created the issue  into freeRtr.
(I'll assign this task to him in GitHub, if not already done)

One reason is that users will be able to follow issue from the organization
repo where I created some labels specific to the project

You are right in a sense that we also might move bitbucket RARE-NIX to
RAR/freeRtr organisation.

Frederic

**Comment by mc36** [comment]
rare 2.0 release? sounds something interesting! :)

**Comment by frederic-loui** [comment]
It is basically a new RARE/freeRtr ONIE with:
1- Latest INTEL SDE LTS 9.11.2
2- Add support for AsterFusion X312
3- improve support for TOFINO2 Edgecore switch
4- latest DEBIAN kernel as of 202304

**Comment by frederic-loui** [comment]
And I forgot the master piece.

- latest/greatest freeRtr as of 20230419

I hope that we can include your last commit so that we can use "string" for
special case such as "100G-R2" AT BF_SWITCHD level.

Le mer. 19 avr. 2023 à 08:11, Frederic LOUI ***@***.***> a
écrit :

> It is basically a new RARE/freeRtr ONIE with:
> 1- Latest INTEL SDE LTS 9.11.2
> 2- Add support for AsterFusion X312
> 3- improve support for TOFINO2 Edgecore switch
> 4- latest DEBIAN kernel as of 202304
>

**Comment by freertr** [comment]
@frederic-loui any news for us???? you have issues, first your mic during your last regular vc at https://geant.zoom.us/j/63276787502?pwd=ei9tQW4yMHJ4UXRpU28xMnhoc1Zjd*** now this timeout, and the pending issues on the containerlab shitload, and the rest of your abandoned projects???

**Comment by freertr** [comment]
@frederic-loui what about uor inbox???? :)
