### ISSUE TITLE
Adjust new interface type for bf_forswarder

### ISSUE THREAD

**Issue by freertr** [rare-freertr/freeRtr#18]
Now that we have [2120e7](https://github.com/rare-freertr/freeRtr/commit/2120e7d8ba8825e5ae87046f0926db527f604921) `bf_forwarder` can be adjusted in order to create corresponding new interface operation mode

**Comment by alexandergall** [comment]
Implemented in https://bitbucket.software.geant.org/projects/RARE/repos/rare/commits/a03aadcd246a645d72b258d17d869f7149e06d5f

The port speed in freertr can now have the number of serdes lanes to use as an optional parameter separated by  a colon, e.g. 100:2. This affects 50G, 100G and 200G on Tofino2. All other Tofino2 ports and all Tofino ports only have one valid choice and the parameter can be omitted.

**Comment by mc36** [comment]
@alexandergall  i just noticed this and your commit to bitbucket, 
((( i was away for more than a month or so, so i shift+del-ed my inbox :) when i got back to my keys )))

so i just committed these:

 https://github.com/rare-freertr/freeRtr/commit/5d5585350facf550331cc32bce9d5b19046ccd00

from now, until further notice, please lemme know when you updated the bitbucket pelase....

ps: the next auto-upgrade to my rare-nix vm will restore this commit on bitbucket....
