### ISSUE TITLE
Issues with RFC9234 (BGP roles) implementation

### ISSUE THREAD

**Issue by user318** [rare-freertr/freeRtr#19]
Hi,

Thanks for implementing RFC9234 in freeRtr! But I've noticed a couple of issues with the implementation:

1) `role ... enforce` configuration enables or disables verification of matching the roles set on local and remote side. The RFC says that the matching should be always done when both sides have the roles configured. And it defines "strict mode", which enforces the other side to configure the role, otherwise the session will not be established.

2) Roles are configured as: `neighbor <ip> role <role_name>`. And it sets the "remote" role, whereas the RFC says the local side defines and announces its local role. For example implementation in [Bird](https://bird.network.cz/?get_doc&v=20&f=bird-6.html#bgp-local-role) uses `local role` configuration for that. So using such "inverse" configuration may be misleading and cause configuration or understanding errors.

3) Not only remote role set in the configuration, but it also advertised to the peer, which is incorrect. I.e. freeRtr instances will interact and work as expected, but it will fail with an RFC-compliant implementation, because it expects "local" role to be advertised by a peer.

**Comment by mc36** [comment]
hi,
https://github.com/rare-freertr/freeRtr/commit/4126700ff9631e32cb9eb57925b332e8890b6f6a should fix this...
now what interops do you suggest for the weekly runs? i just spotted that frr also have this:
https://docs.frrouting.org/en/latest/bgp.html#bgp-roles-and-only-to-customers

https://github.com/rare-freertr/freeRtr/tree/master/cfg

_should_ list intop9-bgp* as frr-bgp-interops, here is the latest run where they are cliclable:

https://groups.io/g/freertr/topic/latest_test_runs/98428978
br,
cs

**Comment by mc36** [comment]
i just did a small change, i'll push it once im pretty sure it does not changes a shit, but helps readability....

 
     /**
      * convert leak to inverted leak
      *
      * @param old old role
      * @return inverted role, -1 on error
      */
     public static int leakInverter(int old) {
         switch (old) {
-            case rtrBgpUtil.roleProv:
-                return rtrBgpUtil.roleCust;
-            case rtrBgpUtil.roleRs:
-                return rtrBgpUtil.roleRsc;
-            case rtrBgpUtil.roleRsc:
-                return rtrBgpUtil.roleRs;
-            case rtrBgpUtil.roleCust:
-                return rtrBgpUtil.roleProv;
-            case rtrBgpUtil.rolePeer:
-                return rtrBgpUtil.rolePeer;
+            case roleProv:
+                return roleCust;
+            case roleRs:
+                return roleRsc;
+            case roleRsc:
+                return roleRs;
+            case roleCust:
+                return roleProv;
+            case rolePeer:
+                return rolePeer;
             default:
                 return -1;
         }
     }
 


that'll be my next commit, and also im pretty sure im in sync with the rfc:


https://datatracker.ietf.org/doc/rfc9234/

https://lists.geant.org/sympa/arc/rare-dev/2023-05/   ctrl+f switchdev, the beginning of the conversation....

**Comment by mc36** [comment]
also see the mailing lists, a bit long but worth the reading: https://lists.geant.org/sympa/arc/rare-dev/2023-05/msg00000.html
