### ISSUE TITLE
ECDSA host key for SSH server is not fully implemented

### ISSUE THREAD

**Issue by alemonmk** [rare-freertr/freeRtr#20]
Hi, I recently discovered freeRtr and set up a VM to replace my core router. I'm grown with Cisco devices so I feel right at home compared to VyOS that I use currently! And finally I can stop following issues regarding VyOS, like [unable to do NAT with VRF](https://vyos.dev/T3655) and the in progress VPP support...

I tried to set up ssh access to freeRtr with this:
```
crypto ecdsa ssh-host-key gen 384

aaa userlist local-users
 user emergency pass *
exit

server telnet ssh
 security protocol ssh
 security auth local-users
 security ecdsakey ssh-host-key
 port 22
 interface sdn0
 vrf Mgmt-intf
exit
```
SSH connection fails immediately. Log from freeRtr says:
```
2023-05-13 02:43:51 traceback secSsh.run:secSsh.java:189 java.lang.NullPointerException: Cannot invoke "net.freertr.cry.cryKeyGeneric.sshWriter()" because "<local4>" is null at secSsh.workerServer:secSsh.java:467/secSsh.run:secSsh.java:186/java.lang.Thread.run:Thread.java:833/
2023-05-13 02:43:51 info prtTcp.connectionRcvd:prtTcp.java:907 got future acknowledge number telnet sdn0 22 -> 10.x.x.x 58095
2023-05-13 02:43:51 info prtTcp.connectionRcvd:prtTcp.java:964 got data while not open telnet sdn0 22 -> 10.x.x.x 58095
2023-05-13 02:43:51 info prtTcp.connectionRcvd:prtTcp.java:907 got future acknowledge number telnet sdn0 22 -> 10.x.x.x 58095
```
From source:
https://github.com/rare-freertr/freeRtr/blob/895b9c41635f0630da95beabd6eea8661065a60b/src/net/freertr/sec/secSsh.java#L466-L467
Things work with RSA key, of course.

**Comment by mc36** [comment]
hi,
thanks for reaching out! so the thing is that, to have any ssh, you need to generate all kind of keys...
this is needed because the ssh server side will offer/reply/etc every kind of key signing, it's completely
up to the client to pick the best fit of it needs... here is a very bad sample on how to enable ssh properly:
https://github.com/rare-freertr/freeRtr/blob/master/cfg/crypt-ssh.tst
also please note that you can do aaa list and configure a sequence of auth methods to try before giving up!
br,
cs

**Comment by alemonmk** [comment]
Hi,
Thanks, though I exclusively use ECDSA/Ed25519 host keys on my other systems. And the fact that freeRtr's SSH works with only RSA keys generated, so I believe having only ECDSA host key should work.

**Comment by mc36** [comment]
it's up to you and your ssh client to choose ecdsa...
ed25519 (the http://cr.yp.to/ curve) is only supported at the moment in the wireguard client...
br,
cs

**Comment by alemonmk** [comment]
I think you have misunderstood me.
For the config above, ssh -vvvv emergency@<router> shows:
```
OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname <router> is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/user/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/user/.ssh/known_hosts2'
debug2: ssh_connect_direct
debug1: Connecting to <router> [<router>] port 22.
debug1: Connection established.
debug1: identity file /home/user/.ssh/id_rsa type -1
debug1: identity file /home/user/.ssh/id_rsa-cert type -1
debug1: identity file /home/user/.ssh/id_dsa type -1
debug1: identity file/home/user/.ssh/id_dsa-cert type -1
debug1: identity file /home/user/.ssh/id_ecdsa type -1
debug1: identity file /home/user/.ssh/id_ecdsa-cert type -1
debug1: identity file/home/user/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/user/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/user/.ssh/id_ed25519 type -1
debug1: identity file /home/user/.ssh/id_ed25519-cert type -1
debug1: identity file /home/user/.ssh/id_ed25519_sk type -1
debug1: identity file /home/user/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/user/.ssh/id_xmss type -1
debug1: identity file /home/user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1
debug1: Remote protocol version 2.0, remote software version freeRouter/23.5.3-cur
debug1: no match: freeRouter/23.5.3-cur
debug2: fd 5 setting O_NONBLOCK
debug1: Authenticating to <router>:22 as 'emergency'
debug3: hostkeys_foreach: reading file "/home/user/.ssh/known_hosts"
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: ext-info-s,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss
debug2: ciphers ctos: aes256-ctr,aes256-cbc,3des-ctr,3des-cbc,blowfish-ctr,blowfish-cbc,rc2-ctr,rc2-cbc,des-ctr,des-cbc
debug2: ciphers stoc: aes256-ctr,aes256-cbc,3des-ctr,3des-cbc,blowfish-ctr,blowfish-cbc,rc2-ctr,rc2-cbc,des-ctr,des-cbc
debug2: MACs ctos: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5
debug2: MACs stoc: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug3: send packet: type 34
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<8192<8192) sent
Connection closed by <router> port 22
```
freeRtr does not offer ECDSA host key at all, and tried to use RSA host keys but since there are no such keys configured the ssh thread gets an exception.

**Comment by mc36** [comment]
yeahhh, as said before, ecdsa (http://cr.yp.to) is considered untrusted here, we only support the curves for vpns like wireguard.

according to https://www.wireguard.com/ it does 1 key exchange / minute and there is no proof that the curve is okay,

moreover all the crypto in wireguard algorihtm comes from the same author, and it's only quantum resistant if you

enable the 3rd parameter (the common shared secret) so at this point, a 8kbit 1kbyte rsa key is easier and does not

requires a per minute job for the cpu.... back to the ssh, re-keying is considered harmful so go generate all the

keys needed for the secSsh.java to not traceback and as an emergency login, please live with the big keys that

hotspot can optimize fine.... yesterday i regenerated the release signing keys based on the very big primes and

after properly warming up the jvm, the java's built in bignumbers class finished the guesstimate under 1sec

and every time i re-ran the 'test digsig keys len 1000" 2000 4000 ... etc command, the generated clang native

gainer measureable milliseconds so thats all....

anyway if you're stick to the curves, feel free to propose a patch that is fine for your needs....

4 your further references please study http://safecurves.cr.yp.to/ and propose a proper one... my personal

favorite would the the ed512xxx because of the more randomness after the /min key exchange....

also please see the rest of the proposed rfcs and how and why they failed over the time...

until that, according to the kiss principle, please live with the simplest diffie-hellam over finite field huuge primes:

https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange : (a^b)%p == (b^a)%p and it's 3loc in java back and forth..

regarding the curvy curves, please see the rest of the src/cry/*EC*java and the in-class static a*b==b*a (multiplication cache)

hacks to finish the key-exchange in a comparable times than the very clever jvm bignum class already provides us...

br,

cs

**Comment by mc36** [comment]
actually tls3 also deprecated re-keying....

and back to the wg, we also support some curves in the rest of the vpns like ikev2 and even in macsec...

and the good news for you is that soon ***@***.*** will finish binging up a new switch target:

a tofino1 asic + 2x (64*arm64 cores) + a x86 cpu to manage the switch, then we can even support

the encryption on the hardware, or even more fun, run the bgp on the arms, or be placeable,

to what to run on them..... ssh, well, i personally do a macsec underlay in my flat and

i manage in telnet from a connection manager... (tplink10gbps managed switches in an mpls vpn)

br,

cs

**Comment by mc36** [comment]
hi,

On 5/13/23 10:34, mc36 wrote:
> ssh, well, i personally do a macsec underlay in my flat and
> 
> i manage in telnet from a connection manager...


and well, authenticating from tacacs with a fallback to a static big random secret xxxxx

the password is recoverable from the cli in rare/freertr much like cisco's type7 encryption on the web... :)

br,

cs

**Comment by alemonmk** [comment]
Had a look at my .known_hosts after reading you reply I use ed25519 only, ECDSA (with unsafe NIST curves) only exist at those that does not support it (i.e. vast majority of commercial network devices).
You have your reasonable opinion on using RSA, if you ever want to implement ed25519 for host key or key exchange, take your time.
Otherwise I can always unbind the management interface from DPDK and use Linux OpenSSH, though I can't easily configure RADIUS for management authentication. Speaking of which, it should have been done, I left none interface to the underlying system, can't get software updates at the moment. 🤣

**Comment by mc36** [comment]
fine! :)

im so sorry, im a way too drank to parse your mansplaining properly so,

(please understand that it's weekend afternoon in my timezone)

so feel free to propose a good patch that does not ruins readability

of the secSsh*.java, secTls*.java and does not make external reviewers heads aches....

thx 4 understanding,

br,

cs

**Comment by mc36** [comment]
to be a just a little bit more polite, im fine with the huuge primes until there is a proof about the curvy-curves :)

as said b4, my all time favorite is the more pseudorandom contents of the *521* from the src/cry/*...

i well know that 4 the low profile arm* cores it's almost line rate but hell 4 a dpdk forwarder,

especially the ipv*/l2tp/ppp/macsec/sgt/mpls/encapsulation we mainly focus in my timezeone,

the cpu is a the thing we must protect the most... regarding the wg.com implementation, i clearly

refuse to initiate the /min handshake until the peer implements the wg.pdf properly i really

dont give a flying fuck... 32*100g in a pizzabox, 4 our 4k intermediate schools its more than

enough, and as we own the optics, we wont turn on crypto at all, so asic all the way is my

primary target in this 'one-man-show'....  :(

(ps: the more pseudorandom content is better, the lower the cpu overhead the better at least 4 me)

br,

cs

**Comment by mc36** [comment]
tbh a bit more honest, it's sunday afternoon and i'm just over my x-th whiskey-soda....

and no on im not an alcoholic or anything....

br,

cs
