### ISSUE TITLE
intop1-isis12 & intop2-isis12 -> "! ipv6 access-group-out test6" why is it in comment ?

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/freeRtr#24]
Hi,
Is the any rationale in having `!` in [`intop1-isis12`](https://raw.githubusercontent.com/rare-freertr/freeRtr/master/cfg/intop1-isis12.tst) & [`intop2-isis12`](https://raw.githubusercontent.com/rare-freertr/freeRtr/master/cfg/intop2-isis12.tst) test case ?

```
...
int eth2
 vrf for v1
 ipv6 addr fe80::1 ffff::
 router isis6 1 ena
 mpls enable
 ipv6 access-group-in test6
! ipv6 access-group-out test6
 exit
...
```

**Comment by mc36** [comment]
disagreeing, its fine on this here... see my last all-tests....

br,

cs

**Comment by mc36** [comment]
but feel free to change my mind or close the issue yourself :)

**Comment by mc36** [comment]
clearly speaking, it helps what?!

**Comment by frederic-loui** [comment]
I'm parsing test case in `cfg` folder tight now. And basically the character `!` has a key role determining if I'm in a `config` or not. In `intop1-isis12` there is this [line](https://github.com/rare-freertr/freeRtr/blob/master/cfg/intop1-isis12.tst#L40) that mislead the parser. I'm just asking if there is a good reason to maintain the line below:

```
! ipv4 access-group-out test4
```
As this line start with a `!` exclamation mark, it is considered as a comment.

If you feel that this line MUST stay, so be it.

I was just asking if there was any rationale behind having this line in comment.

**Comment by mc36** [comment]
yes im sure the tests are fine with this so lemme show your test run that fails because of this....

**Comment by mc36** [comment]
also dont forget to append the "capture r1 eth1 capture r2 eth1" to see if the acl's deny reply is the issue or not...

**Comment by mc36** [comment]
clearly speaking... whats the descirption?!?!?

now what that acl denies?!??!!?!

now whats we're talking about?!!?! XDDD

**Comment by frederic-loui** [comment]
Ok thanks. Got my answer.

**Comment by mc36** [comment]
you're welcome...

**Comment by mc36** [comment]
sorry what was the question in removing an acl in a good working test?!
