### ISSUE TITLE
Unknown config while removing `second-port` in telnet section

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/freeRtr#7]
Hi,

`second-port` cannot be removed.
The curremt work-around is to remove the whole `telnet` section and re-apply it again.

```
FREERTR-MIA0001(cfg)#server telnet oob-nmaas                                                                                                                                                 
RARE-FREERTR-MIA0001(cfg-server)#no second-port 2222                                                                                                                                              
% unknown config command entered
```

Cheers,
Frederic

**Comment by mc36** [comment]
ooohhh this buggy shit, 29ad699c7a78ba22bb3094abaa787d3461e172ad will fix that

**Comment by frederic-loui** [comment]
Thanks for this quick [fix](https://github.com/rare-freertr/freeRtr/commit/29ad699c7a78ba22bb3094abaa787d3461e172ad) !

**Comment by mc36** [comment]
you're welcome and my bad for the inconvenience
