### ISSUE TITLE
Automating md files after each test run

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/freeRtr#8]
Hi,

After regular tests run, new features are implemented and some of them have new entry in [test cases page](http://www.freertr.org/tests.html). Ideally this should update [docs.freertr.org](http://docs.freertr.org/) references documentation section.

This references section needs the following updated files:
1- [index.md](https://github.com/rare-freertr/RARE-web/blob/master/docs/guides/reference/index.md)
2- [tabbed.md](https://github.com/rare-freertr/RARE-web/blob/master/docs/guides/reference/tabbed.md)
3- `_ALL_` test case md files in [raw folder](https://github.com/rare-freertr/RARE-web/tree/master/raw)
4- `json` files describing the topology (computed with [test case definition](http://sources.freertr.org/cfg/))

Is it possible to have these files generated after test run ?

Once done, it will be possible is to automate [docs.freertr.org](https://github.com/rare-freertr/docs.freertr.org) from [RARE-web mkdocs](https://github.com/rare-freertr/RARE-web) with github action. 
(If you are OK I'll do handle this part afterwards)

Therefore we will have an automated up to date reference document based on freeRtr CI/CD     
For now `1`,`2`,`3`,`4` is manually triggered through various post script [here](https://github.com/rare-freertr/RARE-web)

But considering the ultra, fast pace deployment, feature addition and evolution of freeRtr that @mc36 is ensuring , manual trigger update of this documentation is not sustainable anymore. :)
 
Thanks !

**Comment by mc36** [comment]
On 8/29/22 15:31, Frederic LOUI wrote:
> Hi,
> 
> After regular tests run, new features are implemented and some of them have new entry in test cases page <http://www.freertr.org/tests.html>. Ideally this should update 
> docs.freertr.org <http://docs.freertr.org/> references documentation section.
> 
> This references section needs the following updated files:
> 1- index.md <https://github.com/rare-freertr/RARE-web/blob/master/docs/guides/reference/index.md>
my bad, i forgot to generate it, i'll be there starting the next run :)

> 2- tabbed.md <https://github.com/rare-freertr/RARE-web/blob/master/docs/guides/reference/tabbed.md>
it's nothing but a linux shell expression over the csv file previously attached

> 3- |_ALL_| test case md files in raw folder <https://github.com/rare-freertr/RARE-web/tree/master/raw>
i once opened a commit for it and i did't got the email that it was merged

> 4- |json| files describing the topology (computed with test case definition <http://sources.freertr.org/cfg/>)
> 
i already generate the topology in the standard .dot format...
please understand that the simplest the better, and here you only need a directed graph
basically that's what the spf also produce:

mchome-demo>show ipv4 ospf 1 graph 0
2022-08-29 15:36:06
sfdp -Tpng > net.png << EOF
graph net {
//AMS0001
   "AMS0001" -- "FRA0001" [weight=10] [taillabel="10.1.12.1"]
   "AMS0001" -- "POZ0001" [weight=10] [taillabel="10.1.14.1"]
   "AMS0001" -- "PAR0101" [weight=10] [taillabel="10.1.110.1"]
   "AMS0001" -- "TCD0021" [weight=10] [taillabel="10.12.14.1"]
   "AMS0001" -- "SAO0021" [weight=10] [taillabel="10.19.16.1"]
   "AMS0001" -- "PAR0001" [weight=10] [taillabel="10.22.0.1"]
   "AMS0001" -- "CHI0041" [weight=10] [taillabel="10.30.68.1"]
   "AMS0001" -- "10.1.1.1/32" [weight=10]
//FRA0001
   "FRA0001" -- "AMS0001" [weight=10] [taillabel="10.1.12.2"]
   "FRA0001" -- "BUD0001" [weight=10] [taillabel="10.1.23.2"]
   "FRA0001" -- "PAR0101" [weight=10] [taillabel="10.1.210.1"]
   "FRA0001" -- "TCD0021" [weight=10] [taillabel="10.12.13.1"]
   "FRA0001" -- "GVA0001" [weight=10] [taillabel="10.55.9.1"]
   "FRA0001" -- "10.2.2.2/32" [weight=10]
//BUD0001
   "BUD0001" -- "POZ0001" [weight=10] [taillabel="10.1.34.3"]
   "BUD0001" -- "FRA0001" [weight=10] [taillabel="10.1.23.3"]
   "BUD0001" -- "PRA0101" [weight=10] [taillabel="10.3.12.3"]
   "BUD0001" -- "mchome-demo" [weight=10] [taillabel="10.1.39.3"]
   "BUD0001" -- "10.3.3.3/32" [weight=10]
//POZ0001
   "POZ0001" -- "BUD0001" [weight=10] [taillabel="10.1.34.4"]
   "POZ0001" -- "AMS0001" [weight=10] [taillabel="10.1.14.2"]
   "POZ0001" -- "PRA0101" [weight=10] [taillabel="10.4.12.4"]
   "POZ0001" -- "10.4.4.4/32" [weight=10]
//mchome-demo
   "mchome-demo" -- "BUD0001" [weight=10] [taillabel="10.1.39.9"]
   "mchome-demo" -- "10.5.5.5/32" [weight=10]
//PAR0001
   "PAR0001" -- "AMS0001" [weight=10] [taillabel="10.22.0.2"]
   "PAR0001" -- "10.6.6.6/32" [weight=10]
//GVA0001
   "GVA0001" -- "FRA0001" [weight=10] [taillabel="10.55.9.2"]
   "GVA0001" -- "E513-E-YECWH-1" [weight=10] [taillabel="10.12.97.1"]
   "GVA0001" -- "10.7.7.7/32" [weight=10]
//CHI0041
   "CHI0041" -- "AMS0001" [weight=10] [taillabel="10.30.68.200"]
   "CHI0041" -- "BUR0051" [weight=10] [taillabel="10.8.14.1"]
   "CHI0041" -- "RARE-FREERTR-MIA0001" [weight=10] [taillabel="10.8.15.1"]
   "CHI0041" -- "10.0.8.0/31" [weight=10]
   "CHI0041" -- "10.8.8.8/32" [weight=10]
//TCD0021
   "TCD0021" -- "FRA0001" [weight=10] [taillabel="10.12.13.43"]
   "TCD0021" -- "AMS0001" [weight=10] [taillabel="10.12.14.47"]
   "TCD0021" -- "10.9.9.9/32" [weight=10]
//PAR0101
   "PAR0101" -- "AMS0001" [weight=10] [taillabel="10.1.110.10"]
   "PAR0101" -- "FRA0001" [weight=10] [taillabel="10.1.210.10"]
   "PAR0101" -- "mjolnir" [weight=10] [taillabel="10.10.99.10"]
   "PAR0101" -- "10.10.10.10/32" [weight=10]
//PRA0101
   "PRA0101" -- "BUD0001" [weight=10] [taillabel="10.3.12.12"]
   "PRA0101" -- "POZ0001" [weight=10] [taillabel="10.4.12.12"]
   "PRA0101" -- "10.12.12.12/32" [weight=10]
//E513-E-YECWH-1
   "E513-E-YECWH-1" -- "GVA0001" [weight=10] [taillabel="10.12.97.2"]
   "E513-E-YECWH-1" -- "10.13.13.13/32" [weight=10]
//BUR0051
   "BUR0051" -- "CHI0041" [weight=10] [taillabel="10.8.14.2"]
   "BUR0051" -- "BUR0061" [weight=10] [taillabel="10.10.6.1"]
   "BUR0051" -- "10.0.14.0/31" [weight=10]
   "BUR0051" -- "10.14.14.14/32" [weight=10]
//RARE-FREERTR-MIA0001
   "RARE-FREERTR-MIA0001" -- "SAO0021" [weight=10] [taillabel="10.15.16.1"]
   "RARE-FREERTR-MIA0001" -- "CHI0041" [weight=10] [taillabel="10.8.15.2"]
   "RARE-FREERTR-MIA0001" -- "10.0.15.0/31" [weight=10]
   "RARE-FREERTR-MIA0001" -- "10.15.15.15/32" [weight=10]
//SAO0021
   "SAO0021" -- "RARE-FREERTR-MIA0001" [weight=10] [taillabel="10.15.16.2"]
   "SAO0021" -- "AMS0001" [weight=10] [taillabel="10.19.16.2"]
   "SAO0021" -- "10.0.16.0/31" [weight=10]
   "SAO0021" -- "10.16.16.16/32" [weight=10]
//BUR0061
   "BUR0061" -- "BUR0051" [weight=10] [taillabel="10.10.6.2"]
   "BUR0061" -- "10.17.17.17/32" [weight=10]
//mjolnir
   "mjolnir" -- "PAR0101" [weight=10] [taillabel="10.10.99.99"]
   "mjolnir" -- "10.99.99.99/32" [weight=10]
}
EOF

mchome-demo>

if you execute this on a linux, you'll get the _current_ (realtime) topology!!!!!

so generating this graph takes me some ms, well, i already have a tree, and i can do one or other graph 'fancier'
algorithm but it's typically a thing that should not be done at the router... KISS you know from the "csaba is that you email" thread...



> Is it possible to have these files generated after test run ?
> 
surely i'll include the md files starting from today... my bad that i did not that before

**Comment by mc36** [comment]
wontfix

**Comment by mc36** [comment]
well, mostly, the mdfiles for sure, the rest, i already provide them...
the format..
well, easier to do somewhere else.. come on...
the tester is a router exec command "test tester rout-bgp001" spwans up the topology and test on your pe and you can watch it!!! :)
... well, after the proper directory structure, source at hand, including the cfg folder, etc....

**Comment by frederic-loui** [comment]
hi, i absolutely love the dot files. It is just that nextui the Cisco opensource library use this needs this file in order to render [this diagram](http://docs.freertr.org/guides/reference/md/mpls-bier01.tst/) for example. It that could be automated along side md files that would be perfect. So that the tabbed reference view can be updated the diagram

**Comment by mc36** [comment]
then try find some other ui that eats dot files, or a converter from dot to json?
btw have you tried jq? i would be surprised if it would take more than 256 bytes to write the converter yourself....

**Comment by mc36** [comment]
my bad.... https://packages.debian.org/sid/jq

**Comment by frederic-loui** [comment]
Cisco nextui is doing a great job for now. OK let's have a trade off. :)

1- I can provide you a script that create these json files from test case files
2- You'll call this script, each time to issue a test run

the important thing here is to have docs.freertr.org reference rendering the addtion/deletion/modification of new features according to the format required by [RARE-web](https://github.com/rare-freertr/RARE-web)

Automating [docs.freertr.org](docs.freertr.org) reference so that the user have the same information as [freeRTr test case](http://www.freertr.org/tests.html) with diagrams would be awesome.

**Comment by mc36** [comment]
well i would concentrate my resources to the testing...
to have the 3k features run is not much, about 19 minutes
but to have the full zip it takes 8-10 hours
moreover imho you can automate this at github with github actions

**Comment by mc36** [comment]
to catch the idea and dont have to rediscover the wheel, please take a look at rare's per commit security check
(which geant is unable to provide for a year or so)
https://github.com/rare-freertr/freeRtr/blob/master/.github/workflows/codeql.yml
imho you can easily spot the ./c.sh thingy... :)
thanks,
cs

ps: still wont fix

**Comment by frederic-loui** [comment]
ok, just please process md files as per [this format](https://github.com/rare-freertr/RARE-web/blob/master/raw/conn-nos01.tst.md) for example and i'll look at how to leverage github action on how to automate this aftet eahc your automated regular commit.
